Repository EkspoMurinoIndustries/no-thanks, pull requests merged in 2022-12, with the labels that each got.

#6 NT-10: Automate deployment with Github Actions
  .github/workflows/build-and-deploy.yaml
  build.gradle.kts
  deploy/README.md
  deploy/no-thanks.service
Labels: CI/CD

#9 NT-11: Setup `certbot` and `NGINX` proxy server
  .github/CODEOWNERS
  deploy/README.md
  deploy/nginx/default.conf
  deploy/nginx/no-thanks.conf
Labels: deploy

#11 NT-33: Display number of left cards
  src/main/kotlin/org/expo/nothanks/model/event/output/RoundStartedMessage.kt
  src/main/kotlin/org/expo/nothanks/model/event/output/TakeCardMessage.kt
  src/main/kotlin/org/expo/nothanks/service/NotificationService.kt
  src/main/kotlin/org/expo/nothanks/utils/GameUtils.kt
  src/main/resources/static/css/game.css
  src/main/resources/static/index.html
  src/main/resources/static/js/main.js
  src/main/resources/static/js/render.js
Labels: frontend, backend
